export type UiLanguage = 'zh-CN' | 'fr' | 'en';

type Copy = Record<string, string>;

const copy: Record<UiLanguage, Copy> = {
  'zh-CN': {
    appName: '中英法交流助手', newConversation: '＋ 新建对话', localOnly: '本地记录', localNotice: '对话仅保存在当前浏览器；API Key 只在本页面内存中使用。',
    noConversations: '还没有记录。创建一个对话开始吧。', startConversation: '建立一个新对话后，即可逐句记录交流内容。', export: '导出', import: '导入 JSON 备份', remove: '删除', sourceExport: '原文 Markdown', chineseExport: '中文 Markdown', frenchExport: '法语 Markdown', englishExport: '英语 Markdown', jsonExport: '完整 JSON 备份', sourceDocx: '原文 Word', chineseDocx: '中文 Word', frenchDocx: '法语 Word', englishDocx: '英语 Word', sourcePdf: '原文 PDF', chinesePdf: '中文 PDF', frenchPdf: '法语 PDF', englishPdf: '英语 PDF', exporting: '正在准备导出…',
    speaker: '发言者', startRecording: '● 开始录音', stopRecording: '■ 停止录音', recording: '正在录音；每约 4 秒显示一次转写预览。', directInput: '或直接输入', source: '原文', sourcePlaceholder: '实时转写或直接输入本句内容…', detectTranslate: '识别并翻译', translating: '翻译中…', pronunciation: '▷ 发音', original: '原文', translation: '译文', stale: '待重译', manuallyEdited: '已手动修改', translationPlaceholder: '翻译结果将显示于此', previous: '← 上一句', next: '下一句 →',
    usage: '本对话用量', estimate: '本地估算', requests: '次请求', apiSettings: 'API 设置', apiPrivacy: 'API Key 不会保存；刷新或关闭此页面后将清除。CloseAI 地址须含', pricing: '本地计费估算（美元）', pricingNotice: '仅用于本地估算，不代表中转服务的实际账单；刷新页面后恢复默认价格。', sttPerMinute: 'STT / 分钟', textInputPerMillion: '翻译输入 / 百万 tokens', textOutputPerMillion: '翻译输出 / 百万 tokens', ttsPerCharacter: 'TTS / 字符', apiTest: '测试 API', testing: '测试中…', notTested: '尚未测试', help: '帮助', light: '浅色', dark: '深色', language: '界面语言',
    welcomeTitle: '使用前请阅读', welcomeText: '本工具会将录音和待翻译文本发送到你配置的 API 服务（默认 CloseAI）处理。请勿输入不必要的患者姓名、病例号或其他敏感个人健康信息。API 费用由你自己的服务账户承担。', howToTitle: '快速使用', howToText: '1. 在设置中输入 API Key；2. 录音或输入一句话；3. 核对实时转写并点击“识别并翻译”；4. 点击任一语言的“发音”播放。对话只存在此浏览器。', acknowledge: '我已阅读并继续', close: '关闭', wait: '请阅读', seconds: '秒',
  },
  en: {
    appName: 'Chinese–French–English Interpreter', newConversation: '+ New conversation', localOnly: 'Local only', localNotice: 'Conversations stay in this browser. Your API key exists only in this page session.',
    noConversations: 'No records yet. Start a conversation to begin.', startConversation: 'Create a conversation to record each turn.', export: 'Export', import: 'Import JSON backup', remove: 'Delete', sourceExport: 'Original Markdown', chineseExport: 'Chinese Markdown', frenchExport: 'French Markdown', englishExport: 'English Markdown', jsonExport: 'Full JSON backup', sourceDocx: 'Original Word', chineseDocx: 'Chinese Word', frenchDocx: 'French Word', englishDocx: 'English Word', sourcePdf: 'Original PDF', chinesePdf: 'Chinese PDF', frenchPdf: 'French PDF', englishPdf: 'English PDF', exporting: 'Preparing export…',
    speaker: 'Speaker', startRecording: '● Start recording', stopRecording: '■ Stop recording', recording: 'Recording — a transcript preview appears about every 4 seconds.', directInput: 'or type directly', source: 'Source text', sourcePlaceholder: 'Live transcript or type this turn…', detectTranslate: 'Detect & translate', translating: 'Translating…', pronunciation: '▷ Speak', original: 'Original', translation: 'Translation', stale: 'Needs retranslation', manuallyEdited: 'Manually edited', translationPlaceholder: 'Translation appears here', previous: '← Previous', next: 'Next →',
    usage: 'Conversation usage', estimate: 'Local estimate', requests: 'requests', apiSettings: 'API settings', apiPrivacy: 'Your API key is not saved and clears when this page closes or reloads. CloseAI URLs must include', pricing: 'Local price estimates (USD)', pricingNotice: 'Used only for local estimates, not your provider’s bill. Defaults return after a page reload.', sttPerMinute: 'STT / minute', textInputPerMillion: 'Translation input / M tokens', textOutputPerMillion: 'Translation output / M tokens', ttsPerCharacter: 'TTS / character', apiTest: 'Test API', testing: 'Testing…', notTested: 'Not tested', help: 'Help', light: 'Light', dark: 'Dark', language: 'Interface language',
    welcomeTitle: 'Please read before use', welcomeText: 'This tool sends recordings and text to the API service you configure (CloseAI by default). Do not enter unnecessary patient names, case IDs, or other sensitive personal health information. API charges are billed to your own provider account.', howToTitle: 'Quick start', howToText: '1. Enter an API key in Settings. 2. Record or type one turn. 3. Review the live transcript and select “Detect & translate”. 4. Use “Speak” for any language. Conversations remain in this browser only.', acknowledge: 'I have read this — continue', close: 'Close', wait: 'Please read for', seconds: 'seconds',
  },
  fr: {
    appName: 'Interprète chinois–français–anglais', newConversation: '+ Nouvelle conversation', localOnly: 'Local uniquement', localNotice: 'Les conversations restent dans ce navigateur. La clé API existe seulement pendant cette session.',
    noConversations: 'Aucun enregistrement. Créez une conversation pour commencer.', startConversation: 'Créez une conversation pour noter chaque prise de parole.', export: 'Exporter', import: 'Importer une sauvegarde JSON', remove: 'Supprimer', sourceExport: 'Markdown original', chineseExport: 'Markdown chinois', frenchExport: 'Markdown français', englishExport: 'Markdown anglais', jsonExport: 'Sauvegarde JSON complète', sourceDocx: 'Word original', chineseDocx: 'Word chinois', frenchDocx: 'Word français', englishDocx: 'Word anglais', sourcePdf: 'PDF original', chinesePdf: 'PDF chinois', frenchPdf: 'PDF français', englishPdf: 'PDF anglais', exporting: 'Préparation de l’export…',
    speaker: 'Intervenant', startRecording: '● Enregistrer', stopRecording: '■ Arrêter', recording: 'Enregistrement en cours — un aperçu s’affiche environ toutes les 4 secondes.', directInput: 'ou saisissez directement', source: 'Texte original', sourcePlaceholder: 'Transcription en direct ou saisissez cette intervention…', detectTranslate: 'Détecter et traduire', translating: 'Traduction…', pronunciation: '▷ Écouter', original: 'Original', translation: 'Traduction', stale: 'À retraduire', manuallyEdited: 'Modifié manuellement', translationPlaceholder: 'La traduction s’affichera ici', previous: '← Précédent', next: 'Suivant →',
    usage: 'Utilisation de la conversation', estimate: 'Estimation locale', requests: 'requêtes', apiSettings: 'Paramètres API', apiPrivacy: 'La clé API n’est pas enregistrée et est effacée à la fermeture ou au rechargement. Les URL CloseAI doivent inclure', pricing: 'Estimations locales des tarifs (USD)', pricingNotice: 'Utilisées uniquement pour l’estimation locale, et non pour la facture du fournisseur. Les prix par défaut reviennent après rechargement.', sttPerMinute: 'STT / minute', textInputPerMillion: 'Entrée traduction / M tokens', textOutputPerMillion: 'Sortie traduction / M tokens', ttsPerCharacter: 'TTS / caractère', apiTest: 'Tester l’API', testing: 'Test en cours…', notTested: 'Non testée', help: 'Aide', light: 'Clair', dark: 'Sombre', language: 'Langue de l’interface',
    welcomeTitle: 'À lire avant utilisation', welcomeText: 'Cet outil envoie les enregistrements et le texte au service API configuré (CloseAI par défaut). Ne saisissez pas de noms de patients, numéros de dossier ou autres informations de santé sensibles inutiles. Les frais API sont facturés sur votre propre compte.', howToTitle: 'Utilisation rapide', howToText: '1. Saisissez une clé API dans Paramètres. 2. Enregistrez ou saisissez une intervention. 3. Vérifiez la transcription et choisissez « Détecter et traduire ». 4. Utilisez « Écouter » pour chaque langue. Les conversations restent uniquement dans ce navigateur.', acknowledge: 'J’ai lu — continuer', close: 'Fermer', wait: 'Veuillez lire pendant', seconds: 'secondes',
  },
};

export function translator(language: UiLanguage): (key: keyof typeof copy['zh-CN']) => string {
  return (key) => copy[language][key] ?? copy['zh-CN'][key];
}

export const languageLabels: Record<UiLanguage, string> = { 'zh-CN': '中文', fr: 'Français', en: 'English' };
